### ISSUE TITLE
Startseite

### ISSUE THREAD

**Issue by kordianbruck** [Pflegesterne/PFUNK#1]
... details wie die Startseite aussehen soll.

**Comment by renandemelo** [comment]
Ein Prototyp davon steht schon auf https://pflegesterne.bruck.me/pages/

Die Namen vom Prototyp sind im Moment direkt in der Datenbank abgespeichert, aber die können basierend auf den Job automatisch generiert werden. Was für Namen wollen wir bei jedem Post haben?

**Comment by michaelmischke** [comment]
Hi, hier die offenen Punkte von renan:

**Layout** 
Gibt es etwas, das du auf der Hautpseite/Post-Seite anders vorgestellt hast? (es fehlen noch die Kategorienzuordnung und eine Input-box, Komentare unter einem Post hinzufügen zu können)

-> gut wäre nicht nur likes sondern auch downvotes zu ermöglichen
-> ich vermisse einen Button zu den Channels
-> ich vermisse einen button in das persönliche Profil des Nutzers
-> ich vermisse eine einstellung zu den notifications (kann auch ins Profil)


**Posts**. 
Was is die Logik, die beschreibt, welche Posts einem Nutzer angezeigt werden. Im Moment lade ich alles von der Datenbank, was nicht sinnvoll ist. Vielleicht die ersten X Posts (nach Datum sortiert) oder so? 

-> ich fänd eine (für den nutzer wählbare) Sortierung nach "Neuigkeit" (zu letzt gepostet nach oben), "Lautstärke" (die meisten votes nach oben), "Most Commented" (längster thread) sinnvoll (wie im obersten wireframe dargestellt)

**Benutzernamen**. 
Inwieweit sollen Namen verständlich/unverständlich sein? Wollen wir der Autor eines Posts von anderen unterscheiden? Wollen wir zulassen, das ein Nutzer seinen eigenen Benutzernamen definieren kann? Wir können Namen direkt Jodel hat sich selbst ein Muster dafür entwickelt (mit Konzepten wie @OJ, @1, @2). Wir können auch einen Namen automatisch auf Basis vom Job generieren.

-> ich find die Nutzernamen auf basis von Adjektiv plus Berufsbezeichnung super, die sollten dann aber vielleicht wählbar sein (im Profil)

**Avatar**. 
Es sieht relativ ok aus, ein Avatar zu haben (Im moment als person-icon repräsentiert). Vielleicht könnten wir auch ein Avatar bei der Registrierung vorschlagen, wenn der Nutzer seinen Job eingibt.

-> find ich super

**Farbenschema**. 

Was soll die Logik sein, welche Farbe bekommt jeder Post? Darf das sich ändern zwischen Sessions für den gleichen Post? Im moment nehme ich für jeden Post halt die nächste Farbe der Reihenfolge, ohne mir Gedanke darüber zu machen.

das würde ich so lassen, bis es ein Design gibt

**Comment by michaelmischke** [comment]
> Ein Prototyp davon steht schon auf https://pflegesterne.bruck.me/pages/
> 
> Die Namen vom Prototyp sind im Moment direkt in der Datenbank abgespeichert, aber die können basierend auf den Job automatisch generiert werden. Was für Namen wollen wir bei jedem Post haben?

gibt es eine möglichkeit für mich in der Datenbank zu editieren?

**Comment by michaelmischke** [comment]
auf https://pflegesterne.bruck.me/pages/posts/1 - also der Seite zu einem Post und seinen Kommentaren fehlt mir ein "Zurück" Button oder anderweitiger logischer Weg zurück. bitte nutz dafür nicht die Überschrift, ich würd da gerne was explizites haben. Ansonsten wäre das der Screen, in dem gut ein redaktioneller (nicht von einem nutzer) geschriebener Beitrag eingefügt werden könnte (z.B. ein kommentierter Link auf eine externe Seite), den wir später als Fakedoor nutzen und seine Attraktivität messen können.

**Comment by renandemelo** [comment]
> > Ein Prototyp davon steht schon auf https://pflegesterne.bruck.me/pages/
> > Die Namen vom Prototyp sind im Moment direkt in der Datenbank abgespeichert, aber die können basierend auf den Job automatisch generiert werden. Was für Namen wollen wir bei jedem Post haben?
> 
> gibt es eine möglichkeit für mich in der Datenbank zu editieren?

Da muss der @kordianbruck beantworten. Der hat die Infrastruktur selbst aufgesetzt. Darüber hinaus haben wir prototypmäßig auch in Code ein Verhalten eingebaut, dass die Datenbank beim Hochfahren völlig neu erstellt wird. Damit werden alten bei jedem Hochfahren automatisch gelöscht, abet bis dahin kannst du dir mit den Daten testen. Im diesen Verfahren laden automatisch Test-Daten von der Datei (https://github.com/Pflegesterne/frontend/blob/master/server-side/src/model.js#L81). So theoretisch würde es auch gehen, diese Datei manuell zu ändern, um Test-Daten zu erweitern wenn du halt mehrere Posts willst.

**Comment by michaelmischke** [comment]
> > > Ein Prototyp davon steht schon auf https://pflegesterne.bruck.me/pages/
> > > Die Namen vom Prototyp sind im Moment direkt in der Datenbank abgespeichert, aber die können basierend auf den Job automatisch generiert werden. Was für Namen wollen wir bei jedem Post haben?
> > 
> > 
> > gibt es eine möglichkeit für mich in der Datenbank zu editieren?
> 
> Da muss der @kordianbruck beantworten. Der hat die Infrastruktur selbst aufgesetzt. Darüber hinaus haben wir prototypmäßig auch in Code ein Verhalten eingebaut, dass die Datenbank beim Hochfahren völlig neu erstellt wird. Damit werden alten bei jedem Hochfahren automatisch gelöscht, abet bis dahin kannst du dir mit den Daten testen. Im diesen Verfahren laden automatisch Test-Daten von der Datei (https://github.com/Pflegesterne/frontend/blob/master/server-side/src/model.js#L81). So theoretisch würde es auch gehen, diese Datei manuell zu ändern, um Test-Daten zu erweitern wenn du halt mehrere Posts willst.

mega gut, danke dir. kannst du mir noch schreiben, wo der header ist, ich würd da gerne Pflegesterne, statt Plegesterne schreiben:-)

**Comment by renandemelo** [comment]
> > > > Ein Prototyp davon steht schon auf https://pflegesterne.bruck.me/pages/
> > > > Die Namen vom Prototyp sind im Moment direkt in der Datenbank abgespeichert, aber die können basierend auf den Job automatisch generiert werden. Was für Namen wollen wir bei jedem Post haben?
> > > 
> > > 
> > > gibt es eine möglichkeit für mich in der Datenbank zu editieren?
> > 
> > 
> > Da muss der @kordianbruck beantworten. Der hat die Infrastruktur selbst aufgesetzt. Darüber hinaus haben wir prototypmäßig auch in Code ein Verhalten eingebaut, dass die Datenbank beim Hochfahren völlig neu erstellt wird. Damit werden alten bei jedem Hochfahren automatisch gelöscht, abet bis dahin kannst du dir mit den Daten testen. Im diesen Verfahren laden automatisch Test-Daten von der Datei (https://github.com/Pflegesterne/frontend/blob/master/server-side/src/model.js#L81). So theoretisch würde es auch gehen, diese Datei manuell zu ändern, um Test-Daten zu erweitern wenn du halt mehrere Posts willst.
> 
> mega gut, danke dir. kannst du mir noch schreiben, wo der header ist, ich würd da gerne Pflegesterne, statt Plegesterne schreiben:-)

Sorry :D

Hier ist es: https://github.com/Pflegesterne/frontend/blob/master/client-side/src/app/top-bar/top-bar.component.html#L6

**Comment by michaelmischke** [comment]
> > mega gut, danke dir. kannst du mir noch schreiben, wo der header ist, ich würd da gerne Pflegesterne, statt Plegesterne schreiben:-)
> 
> Sorry :D
> 
> Hier ist es: https://github.com/Pflegesterne/frontend/blob/master/client-side/src/app/top-bar/top-bar.component.html#L6

alles klar, hab ich gemacht....kannst du die beiden Änderungen dann mergen? beim nächsten mal kommentiere ich meine edits...hab ich jetzt vergessen, tut mir leid

**Comment by renandemelo** [comment]
> > > mega gut, danke dir. kannst du mir noch schreiben, wo der header ist, ich würd da gerne Pflegesterne, statt Plegesterne schreiben:-)
> > 
> > 
> > Sorry :D
> > Hier ist es: https://github.com/Pflegesterne/frontend/blob/master/client-side/src/app/top-bar/top-bar.component.html#L6
> 
> alles klar, hab ich gemacht....kannst du die beiden Änderungen dann mergen? beim nächsten mal kommentiere ich meine edits...hab ich jetzt vergessen, tut mir leid

Da musste ich nichts tun. Du hast selbst einen Commit auf "master" gemacht und das wurde automatisch gebaut und auf https://pflegesterne.bruck.me/pages/ released. Diese "Release-Pipeline" hat der @kordianbruck auch aufgesetzt.

**Comment by michaelmischke** [comment]
Diese "Release-Pipeline" hat der @kordianbruck auch aufgesetzt.

fett! Danke

**Comment by michaelmischke** [comment]
The + button should be visible also on small mobile devices 
currently the headline stays in one line and only the refresh icon stays visible...see screenshot. 

Maybe the issue is not relevant, if the product name (which will be decided and announced tomorrow) is shorter, but maybe the headline could brake into two lines....
![IMG_625450D693F0-1](https://user-images.githubusercontent.com/66677543/85985887-ad0d3b00-b9eb-11ea-9f55-3d563994a17e.jpeg)
