### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by michaelmischke** [Pflegesterne/PFUNK#19]
- [ ] Users* have the possibility to see notifications via a button on the main screen of the application.

- [ ]  Notifications are sent for up-or down-votes, comments, new pfunks on a channel a user follows, admin bans.

- [ ] The application sends an OS notification on the smartphone when activated by the user.

**Comment by michaelmischke** [comment]
@renandemelo

**Comment by ConnyR** [comment]
approved

**Comment by mitunsleben** [comment]
Closed during feature review in AUG 2020
