### ISSUE TITLE
Android Web App with Notifications

### ISSUE THREAD

**Issue by michaelmischke** [Pflegesterne/PFUNK#20]
- the servcie is available as a web app in Android's playstore
- the system should sent full notifications

**Comment by JSchroeder-contec** [comment]
What is meant by notifications.

**Comment by michaelmischke** [comment]
A web app is an app that runs a website in a hidden browser. Possible people call it a wrap app;-) 

System notification means your smartphone notificationsystem notifies you when something new happens so that you don’t have to check. Notifications are using the same elements all other apps use

**Comment by ConnyR** [comment]
approved :)

**Comment by mitunsleben** [comment]
Issue 21 geschlossen; vorhandener/ gewünschter Funktionsumfang der Notifications in den verschiedenen Systemen ist zu klären
