### ISSUE TITLE
Admin functions, e.g. moderation and user-blocking

### ISSUE THREAD

**Issue by ConnyR** [Pflegesterne/PFUNK#23]

**Comment by LimNora** [comment]
- [ ] As admin I can filter the feed for posts that are downvoted (most) and delete them. 
- [ ] As admin I can ban user permanently or temporarily. Ideally the user should be recognized by his device, so that he/she cannot log in with a new account. 
- [ ] As admin I can display the posts that have been marked as problematic (by downvoting) either by users or ideally automatically (e.g GCP Data Loss Prevention API). I can then delete these posts.

**Comment by ConnyR** [comment]
approved

**Comment by JSchroeder-contec** [comment]
final changes concerning dashboard, hashtags and channels - approved

**Comment by michaelmischke** [comment]
Renan schrieb: 

Admin bereich:
Admin-Kontos werden durch eine Flag definiert (in der Datenbank). Zwei Administrator-Nutzer werden automatisch beim Hochfahren erstellt (https://github.com/Pflegesterne/frontend/blob/master/server-side/src/model.js#L138)
E-mail: admin@admin.com, passwort: admin
E-mail: another@admin.com, passwort: another
Kategorien Bearbeiten (nur für Admin-Nutzer)
Kategorien erstellen
Kategorien zusammenführen (statt löschen wegen anhängigen Posts)
Abonnements der alten Kategorien in die Neue
Posts der alten Kategorien in die Neue zusammenführen

**Comment by michaelmischke** [comment]
I managed to create channels, and to edit their names and to merge them, 
![Bildschirmfoto 2020-07-14 um 21 02 31](https://user-images.githubusercontent.com/66677543/87465938-bca89880-c615-11ea-828a-aad5950344e0.png)
![Bildschirmfoto 2020-07-14 um 21 02 41](https://user-images.githubusercontent.com/66677543/87465946-be725c00-c615-11ea-957c-7b26eb1c49af.png)
![Bildschirmfoto 2020-07-14 um 21 02 57](https://user-images.githubusercontent.com/66677543/87465948-bf0af280-c615-11ea-870d-f5f9f984227f.png)


but how can they be deleted?

**Comment by renandemelo** [comment]
Hi Michael,

As I mentioned in my email from last week I implemented merging channels as an alternative for removing channels. The main reason was that there might exist posts pointing to them and users subscriptions. These posts and user subscriptions would still have to be associated to another channel even after the original channel is deleted. Merging channels solve this problem. 

In practice you can literally merge channel A and B into a channel A. This would be equivalent of removing channel B, but migrating all posts and user subscriptions from channel B to channel A.

**Comment by mitunsleben** [comment]
**Enable Channel as favorite to all users:** Sollen die Kanäle nur als "aboniert" zu den Nutzereinstellungen hinzugefügt werden oder unabhängig von den Nutzereinstellungen immer angezeigt werden? Soll der Nutzer in der Lage sein diese Einstellung eigenstänig zu entfernen?

**Delete Channel:** Merging ist eine gute Möglichkeit "orphaned Posts" zu vermeiden, jedoch ist es dadurch nicht möglich im Batch-Modus z.B. unangebrachte Posts zu entfernen. So gewollt?

**Freischaltung/ Banning von Posts:** Sollen Posts automatisch (nach einer automatischen Prüfung) freigeschalten werden oder vorab eine (semi-)manuelle Prüfung durch die Administratoren erfolgen?

**Comment by mitunsleben** [comment]
Closed by feature list review in AUG 2020
