### ISSUE TITLE
Colour assignments (& font)

### ISSUE THREAD

**Issue by ConnyR** [Pflegesterne/PFUNK#24]
random. every post gets a colour. comments to a post have the same colour as the post itself
There is no special colour for special channels. everything is random :D
Our colours for backgrounds of the posts are: 
sRGB 51/0/204
sRGB 181/41/139
sRGB 253/81/0
sRGB 252/220/0

font colour:
sRGB 0/0/0
Font: 
Montserrat

**Comment by JSchroeder-contec** [comment]
approved

**Comment by mitunsleben** [comment]
Closed by Feature Review AUG 2020
