### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by michaelmischke** [Pflegesterne/PFUNK#27]
- [x] users can comment posts

- [ ] users can comment comments

- [ ] the editor for the comments (regarding a post) opens below the list of comments 

- [x] there is only one thread for each post

- [ ] comments on comments are visible via reference to the author of the original comment via @username (like on jodel)

- [ ] the editor for the comments on comments (which could be also editorial (from the admins) opens under the selected comment

**Comment by JSchroeder-contec** [comment]
approved

**Comment by ConnyR** [comment]
approved

**Comment by hauptstadtbytes** [comment]
**Comment a comment:** Wie tief soll die Baumstruktur gehen? Wie kann dies noch übersichtlich dargestellt werden?

**Comment by mitunsleben** [comment]
closed by feature list review in AUG 2020
