### ISSUE TITLE
edit posts, up and down voting of posts

### ISSUE THREAD

**Issue by michaelmischke** [Pflegesterne/PFUNK#28]
- [ ] users can write a post with maximum 500 characters

- [ ] users are offered an empty field for their post with the text "Platz für Deinen Pfunk - Geschichten und Fragen aus Deinem Alltag"

- [ ] users can freely assign hashtags

- [ ] existing hashtags are offered in a list as soon as the user has typed the first two characters

- [ ] users can delete their own posts

- [ ] as soon as a post is deleted, comments are deleted as well

- [x] user can upvote posts and comments

- [ ] users can downvote posts and comments

- [ ] users see the sum of the up and downvotes on every post and comment

- [ ] posts and comments with 10 downvotes are hidden for users

- [ ] admins can see most downvoted posts and comments in the backend and can delete them

**Comment by JSchroeder-contec** [comment]
approved

**Comment by JSchroeder-contec** [comment]
deleting of posts added

**Comment by JSchroeder-contec** [comment]
postig opf posts added

**Comment by hauptstadtbytes** [comment]
**Bug:** Erstellen neuer Posts nicht möglich; nach Anklicken von "Senden", wird kein Post erstellt

**Bug:** Upvoting kann zwar angeklickt werden, verändert aber nicht das Voting (den Wert in der DB)

**Downvoting:** Welche Auswirkungen soll ein "Donwnvoting" genau haben (nur Anzeige weiter hinten im Feed)? Welche Auswirkungen soll ein "Hiding" nach 10 Downvotes haben (z.B. Anzeige im Admin-Dashboard nur erneuten Freischaltung)? Wie wird Missbrauch verhindert? -> Diskussion notwendig

**Löschen:** Sollen die Inhalte (Post + Kommentare) permanent aus der DB gelöscht werden oder nur "als gelöscht markiert" und ausgebendet werden?

**Comment by mitunsleben** [comment]
closed by feature list review in AUG 2020
