### ISSUE TITLE
editorial posts and comments

### ISSUE THREAD

**Issue by michaelmischke** [Pflegesterne/PFUNK#29]
- [ ] admins can enter and post "editorial comments" on posts and comments

- [ ] editorial posts can include web links within a white-list of adressable domains: pflegesterne.de (plus maybe others)

- [ ] editorial posts look like user generated posts and comments (no different frame)

- [ ] editorial posts can belong (tags) to different categories (tipps &tricks, knowledge, job offers, etc)

- [ ] editorial posts comprise extra channels (Tipps& tricks, knowledge, job offers, etc.) (Prio 2)

**Comment by ConnyR** [comment]
approved :)

**Comment by hauptstadtbytes** [comment]
**Look & Feel:* Um ggf. "extern hinzugekommene" Stories einzupflegen, sollten Editorial Posts wie Nutzer-Posts aussehen **können**, sollten sich aber ggf. (u.a. zu Moderationszwecken) von ihnen unterscheiden. Hinweise zu externen Zusatzinformationen, neuen Kategorien etc. sollten ggf. direkt an die jeweiligen Posts/ Kommentare gelabled werden, u.a. um zu verhindern, dass sie in langen Post- oder Kommentarlisten "untergehen".

**Comment by mitunsleben** [comment]
closed by feature list review in AUG 2020
