### ISSUE TITLE
Add Post

### ISSUE THREAD

**Issue by hauptstadtbytes** [Pflegesterne/PFUNK#3]
- [ ] Moderation function: As admin I can delete every post and comment.
- [ ] As a user I can mark a post as inappropriate. (Prio 2)
- [ ] As a user, I can comment, up- and down-vote each post to express my agreement or disagreement, with the same functionality of the editor as when creating a post. 

- [ ] Design ideas: Either open the post as a separate window or unfold it in the feed (accordion) 

- [x] As a user I can create a contribution: 
- [x] Necessary input:
- [x] Content (max. number of characters TBD. Somewhere between 240 and 2000)
- [ ] Category(s) list (free text with Typahead proposal of already existing categories)
- [x] Editor
- [ ] support for text (bold, italic, underlined), external links and hashtags
- [x] no support for images and media files
- [ ] Support for Emojis

Beispiel Jodel Post
![jodel_post_detail](https://user-images.githubusercontent.com/47249813/84398107-d06c7380-abff-11ea-9fee-3bbbee0d6004.png)

Alternativer Designvorschlag
![New Story](https://user-images.githubusercontent.com/40124201/84355531-0e977200-abc3-11ea-9fce-90ab62c63f21.png)

**Comment by mitunsleben** [comment]
Closed by feature list review in AUG 2020
