### ISSUE TITLE
Reporting

### ISSUE THREAD

**Issue by JSchroeder-contec** [Pflegesterne/PFUNK#30]
- [ ] User can report a post or comment as spam, violation of Pfunk nettikette or breach of law. To do so, you click on "..." in the right side of the post and select "Pfunk melden (=reported posts)" or "Pinnen" in the menu.

- [ ] Reported posts or comments are directly shown in the admin dashboard.

- [ ]  Pinned posts are put on top of the personal feed.

- [ ] If a post or comment is reported five times or more it is automatically blocked.

**Comment by hauptstadtbytes** [comment]
**Pinning:** Wie soll damit umgegangen werden, wenn "zu viele" Post gepinnt werden? Theoretisch würde damit ein komplette Auszeige aus "nur gepinnten Posts" entstehen können.

**Comment by mitunsleben** [comment]
Closed by Feature Review in August 2020
