### ISSUE TITLE
Userprofile

### ISSUE THREAD

**Issue by michaelmischke** [Pflegesterne/PFUNK#31]
User can create their profile when starting the App and access it via a button on the mainscreen

- [ ] edit their job from a dropdown selection

- [x] manage their subscriptions to channels

- [ ] see latest posts, followed posts, comments on own posts

**Comment by hauptstadtbytes** [comment]
Subscription management available. 

-> To be concepted/ done in follow-up

**Comment by mitunsleben** [comment]
Closed by feature list review in AUG 2020
