### ISSUE TITLE
Userprofil

### ISSUE THREAD

**Issue by LimNora** [Pflegesterne/PFUNK#6]
- [ ]  Users can choose type of notifications within the profile.
- [ ] User recceive an assurance that we work DSVGO conform. 
- [ ] Als User kann ich ein Profil erstellen und folgende Informationen einpflegen:

 Verpflichtend: Job (Auswahl Angehöriger, Krankenpfleger/in, Altenpfleger/in, Pflegehelfer/in, Pflegemanager/in, Sonstige)
Mehrfachauswahl möglich. 
Optional: Ort, Alter, Ausbildung (Freitext) 

- [ ] Als User kann ich mein Profil jederzeit löschen. Kommentare und Posts bleiben allerdings bestehen.

**Comment by michaelmischke** [comment]
left over aspects of this ticket:

- [ ] access to profile from main screen

- [ ] channel abonnements in profile

- [ ] password free id of user via imei or similar (prio 2)

- [ ] profile deletion (content stays)

- [ ] analytics enable analysis of users via id in database

- [ ] selection of job/education via icons/buttons (prio 2) 

- [ ] additional menu items in profile (Prio 2)

- "News" here comes admin content
- "My Pfunks" the self posted posts appear
- "My comments" self-explanatory
- "My votes" the posts and comments that I voted up or down
- "My favorites" my favorite, if I put a star on it (pinned) (prio 3)

**Comment by mitunsleben** [comment]
**Status Quo:** Nutzer wird bei der Registrierung nach E-Mail, Passwort und Job (Auswahl aus Dropdown) gefragt. Es gibt die Menüoptionen "Abmelden", "Subscriptions" und "Neue Post", aber kein klassisches Profilmanagement.

**Comment by mitunsleben** [comment]
Closed by feature review in AUG 2019
