### ISSUE TITLE
Community Rules

### ISSUE THREAD

**Issue by LimNora** [Pflegesterne/PFUNK#7]
- [ ] After login the user gets the rules displayed and has to accept them all at once. 

- [ ] rules: tbd

- Do not share personal or patient information. No names of patients, colleagues, institutions or companies. 
- Treat everyone with respect. No personal attacks. Do not have arguments. Save your energy for other things. If anyone breaks the rules, report the contribution to the admins.

**Comment by michaelmischke** [comment]
- [ ] this should be realized through a popup, visible before editign the first post (just like in jodel.com)

**Comment by JSchroeder-contec** [comment]
approved

**Comment by mitunsleben** [comment]
Closed by Feature Review in AUG 2020
