### ISSUE TITLE
Follow & create channels

### ISSUE THREAD

**Issue by LimNora** [Pflegesterne/PFUNK#9]
- [x] user can select channels through a menu on the main screen

- [ ] the list of channels user can select from is a mix of admin proposals and search results (default is the best channels defined by admins)

- [x] As a user I can follow different channels, which were created by the admins 

- [x] users can select the channels in a radio button style menu in their profil and in a menu accessible from the main screen via a short cut button

- [x]  As a user I can't create a new channel. Only admins can create channels (following the usage of hashtags)

- [ ]  As soon as a new channel is created all posts and comments which have used the hashtag (=name of the channel) or will use the hashtag are sorted into the channel

![Profile_interests_page](https://user-images.githubusercontent.com/47249813/84996170-33549200-b14d-11ea-86ae-aa5c92d39622.png)

**Comment by JSchroeder-contec** [comment]
Delete text "abonniert" - just the check box is OK

**Comment by ConnyR** [comment]
approved

**Comment by renandemelo** [comment]
I created today the concept of categories in the system.

Now every post needs to be associated to a predefined category.  This is being loaded from the database, but in the future to be managed via an admin area in the application.

Registration: Users get by default subscribed to all categories in the registration. 

New Post: Users will see list of existing categories (now coming from a database)

Manage subscriptions: Users can now view and change their subscriptions via an item in the menu.

Feed: Only posts related to subscribed categories will be shown in the feed, creating a personalized experience.
Users have an item in the menu to change their subscriptions. Changing subscriptions now have an effect on the feed page, and users will only see posts related to the subscribed categories.

**Comment by michaelmischke** [comment]
email from Renan regarding status from Friday: 

I created today the concept of categories in the system.

Now every post needs to be associated to a predefined category. This is being loaded from the database, but in the future to be managed via an admin area in the application.

Registration: Users get by default subscribed to all categories in the registration.

New Post: Users will see list of existing categories (now coming from a database)

Manage subscriptions: Users can now view and change their subscriptions via an item in the menu.

Feed: Only posts related to subscribed categories will be shown in the feed, creating a personalized experience.
Users have an item in the menu to change their subscriptions. Changing subscriptions now have an effect on the feed page, and users will only see posts related to the subscribed categories.

**Comment by mitunsleben** [comment]
Closed during feature review in AUG 2020
